Feat: Add base implementation of kernel smart account with ECDSA validator
pimlicolabs/permissionless.js pull request #42
Opened 2023-11-22 19:11 UTC by KONFeature

- Add the `signerToEcdsaKernelSmartAccount` method to generate and use Kernel smart account that use an ecdsa validator. 
- Use a separated folder inside account, `kernel/`, for other validator implementation in the long term

2023-11-23 05:51 UTC, plusminushalf commented
Hey! Thanks for contributing to permissionless.

This PR It looks like a great start and I have a few questions and comments:

1. We don't need the whole ABI - `src/accounts/kernel/abi/KernelAccountAbi.ts`. We just need `executeBatch`, `execute` & `initialize`. If we can just include them and exclude the rest of abi it will save us on size.
2. Is there a module support in the kernel? Do we need to enable them during initialization?
3. Do kernel support execution during the setup/initialisation phase? This could be helpful for erc20 paymasters where you would like to approve USDC during initialisation so that paymaster already have access to approved USDC. This will allow paying for deployment of SCW with USDC.

2023-11-23 10:37 UTC, KONFeature commented
Hey! 
1. ABI cleanup pushed
2. Yeah they support module for the userOp validation phase, the activation of the ECDSA one is actually done during the createAccount phase (that's what we have in the `getAccountInitCode(...)` method, the `initialisationData` is here to enable the ECDSA module)
3. Unfortunately no , they don't support that yet :/

2023-12-07 11:44 UTC, plusminushalf requested changes

2023-12-07 11:44 UTC, plusminushalf commented on src/accounts/kernel/signerToEcdsaKernelSmartAccount.ts
> +            return concatHex(["0x00000000", signature])
what do you mean by "since we will use external paymaster"? Will this impact others using this library?

2023-12-07 11:44 UTC, plusminushalf commented on src/clients/createSmartAccountClient.ts
> + *  - Fix typing, 'accounts' is required to signMessage, signTypedData, signTransaction, but not needed here, since account is embedded in the client
This is not needed, as in viem in `signTransaction` you can have a client without an account and attach the client to any of the above function calls separately.

2023-12-07 11:44 UTC, plusminushalf commented on src/accounts/kernel/signerToEcdsaKernelSmartAccount.ts
> +            throw new Error("Invalid owner for the already deployed account")
Can we define a custom error for this?

2023-12-07 13:23 UTC, plusminushalf approved these changes

2023-12-07 13:24 UTC, merged